#pragma once

enum EAchievementID : uint32_t
{
    eAchievementID_StillBroken = 24,
    eAchievementID_LookingBetter,
    eAchievementID_StillAJigsawPuzzle,
    eAchievementID_PickingUpThePieces,
    eAchievementID_AlmostThere,
    eAchievementID_OneMoreToGo,
    eAchievementID_WorldSavior = 31,
    eAchievementID_PartlyCloudy,
    eAchievementID_Sunny,
    eAchievementID_HalfMoon,
    eAchievementID_FullMoon,
    eAchievementID_BlueStreak,
    eAchievementID_PowerOverwhelming,
    eAchievementID_GettingTheHangOfThings,
    eAchievementID_CreatureOfTheNight,
    eAchievementID_HelpingHand,
    eAchievementID_LayTheSmackdown,
    eAchievementID_WallCrawler,
    eAchievementID_Airdevil,
    eAchievementID_Hyperdrive,
    eAchievementID_Basher,
    eAchievementID_Smasher,
    eAchievementID_Crasher,
    eAchievementID_Thrasher,
    eAchievementID_SocialButterfly,
    eAchievementID_HungryHungryHedgehog,
    eAchievementID_AcePilot,
    eAchievementID_DayTripper,
    eAchievementID_HardDaysNight,
    eAchievementID_GetOnTheExorciseBandwagon,
    eAchievementID_GyroWithRelish = 64,
    eAchievementID_PigInABlanket,
    eAchievementID_ExoticToppings,
    eAchievementID_SausageFriedRice,
    eAchievementID_IcedHotdog,
    eAchievementID_KebabOnABun,
    eAchievementID_KetchupAndMustard,
    eAchievementID_HardBoiled,
    eAchievementID_FriedClamRoll,
    eAchievementID_FirstTimeCustomer,
    eAchievementID_OhYouShouldntHave,
    eAchievementID_ThatsEnoughSeriously,
    eAchievementID_Hedgehunk,
    eAchievementID_IAintAfraidOfNoGhost,
    eAchievementID_BFFs,
    eAchievementID_SpeedingTicket,
    eAchievementID_ComboKing,
    eAchievementID_RingLeader,
    eAchievementID_KnockoutBrawler,
    eAchievementID_BlueMeteor
};
